### ISSUE TITLE
EROFS: read-only file system

### ISSUE THREAD

**Issue by Chrizz604** [Angelmaneuver/wallpaper-setting#1]
Hey there, I recently switched from windows 10 to Ubuntu 20.04.2 LTS and now I'm having some issues while trying to setup an background image, any Idea on how to fix this issue?

### Error:
> EROFS: read-only file system, open '/snap/code/70/usr/share/code/resources/app/out/bootstrap-window.js'

**Comment by Angelmaneuver** [comment]
Hi Chrizz604.
I'll answer for your question.

### How to use it on Ubuntu
- Install from a deb file instead of installing from the Snap Store, and grant write permission to bootstrap-window.js.

![screen shot](https://user-images.githubusercontent.com/64075949/128246321-76980fc2-fc2c-47b8-a7a6-94f9ebcbaed8.jpg)

### Error Reason
This extension is realized by inserting JavaScript to set the background in VSCode's bootstrap-window.js.
Applications installed from the Snap Store are read-only and cannot do it.
It is also not possible to grant write permisssion to them. (Reference source [it](https://askubuntu.com/questions/762354/where-can-ubuntu-snaps-write-data.))

Therefore, if you want to use VSCode installed from Snap Store, you will have to give up using this extension.

### Supplement
This extension makes the following two changes.

1. "VSCode installation directory" /resources/app/out/bootstrap-window.js
2. settings.json

Since bootstrap-window.js could not be changed due to the error, you can restore the clean state before the error by deleting the setting values starting with "wallpaper-setting." from settings.json.

Thanks for reporting the issue.
If there are no additional questions, I'll close this issue in about week.

**Comment by Chrizz604** [comment]
Thanks!
