### ISSUE TITLE
Wallpaper doesnt appear as well

### ISSUE THREAD

**Issue by AlvinSetyaPranata** [Angelmaneuver/wallpaper-setting#10]
Hi, currently i'm installing this extension in my other computer with the previous version which is easy to configure with, but now i feel like it's to complicated to me when i want to set background usually it will ask me how much the opacity that i want, but now when i select the image for the background it directly notice me to restart the vscode, and when i re open the image appear shortly and then it's gone i try to use optimize but still didn't work, so how can i set the image background, i didn't use slides

**Comment by Angelmaneuver** [comment]
Hi AlvinSetyaPranata.
Can you tell me what theme you are using?

Maintaining both normal and advanced modes is a hassle and I have no intention of bringing them back because I don't use them myself.
There are other excellent extensions that set the background, so if it's too much trouble, you could move on to those.

If there are no additional questions, I'll close this issue in about week.

**Comment by AlvinSetyaPranata** [comment]
i'm using tokyo night color theme

**Comment by Angelmaneuver** [comment]
<img width="1440" alt="sample" src="https://github.com/Angelmaneuver/wallpaper-setting/assets/64075949/e197d9c5-9a66-4894-b938-c47a94043a48">

I don't know if it is the same since there were many similar extensions, but it worked in my environment.

If the optimization was successful, the color information should be added to the settings.json of the profile in the form of [theme name in use].

**Comment by AlvinSetyaPranata** [comment]
can u provide the tutorial how to set the background because i'm still confused :)

**Comment by AlvinSetyaPranata** [comment]
should i set the color theme first or the wallpaper first?

**Comment by Angelmaneuver** [comment]
I'm sorry, Please use similar background setting extensions.

Unfortunately, I don't think there is any need to put any more effort into this extension.

You have been using the normal mode, you should be able to move on other extensions.
