### ISSUE TITLE
Process explorer

### ISSUE THREAD

**Issue by d0ob** [Angelmaneuver/wallpaper-setting#2]
Hi there !
I love the extension, it's really practical and well-made, who doesn't love customization when it's that easy ! 
But the wallpaper I use render an unreadable process explorer ! Could this explorer be blacklisted or something ?
It's not a massive issue, I just toggle it off if I ever have to use it, wich isn't frequent lol But I thought I could ask ! 

Thanks !

**Comment by Angelmaneuver** [comment]
Hi d0ob.
I'll answer for your bug report.

The broken display in Process Explorer was an unintentional bug.
So we fixed it so that the wallpaper is not set in Process Explorer.

We hope you won't have any trouble with the new version.
In the future, we will investigate whether we can make it possible to set the wallpaper in Process Explore.

Thanks for reporting the issue.
If there are no additional questions, I'll close this issue in about week.

**Comment by d0ob** [comment]
Hi ! Yes I just saw the update ! Much better ! =)
I thought it hadn't solved anything at first, but I just had to reload my wallpaper ^^ 

Well, in fact, now I think of it : I suppose the real issue was to not share the opacity, because it could be nice to have the wallpaper here too, otherwise ! I don't know what is the most practical to implement though, and since you already solved it that way, you maybe don't want to mind that ^^ But both satisfy me !  

Thanks much for the consideration and the quick fix !
