### ISSUE TITLE
"You don't have permission to write to the file required to run this extension. Please check the permission on "/usr/share/code/resources/app/out/bootstrap-window.js"

### ISSUE THREAD

**Issue by crhodes2** [Angelmaneuver/wallpaper-setting#3]
...and that error is coming from a fresh installation of VS Code via Linux, using the terminal
**sudo apt-get install "vs code package name"**

Basically, I have read the Cautions section of this extension profile, stating verbatim
_"bootstrap-window.js" requires write permission. Therefor, this extension cannot be used with VSCode installed from "Snap Store" App Store for Linux (Because write permission cannot be granted)._

So here I go to uninstall VS Code from my machine and redownloaded it straight from the VS Code website, using two different packages: as a .deb package and as a .tar.gz package. And NONE of those allow me to move past the error.

What am I doing wrong? Am I missing something? Or has this dumb program run its course? There has not been any strong wallpaper extensions in code and I thought this was it.

**Comment by Angelmaneuver** [comment]
As you can see in the error message, the process running VScode does not have permission to write to the target file.

Please set the permission so that the process running VScode can write to the target file.

In addition to permissions, RHEL systems may not be able to write due to SELinux.
We are not aware of such distribution-specific security features, so please investigate on your own.

If there are no additional questions, I'll close this issue in about week.
